export const LOAD_INITIAL_ADDRESSES = 'LOAD_INITIAL_ADDRESSES'
export const LOAD_INITIAL_USERS = 'LOAD_INITAL_USERS';

export const CREATE_ADDRESS = 'CREATE_ADDRESS';
export const DELETE_ADDRESS = 'DELETE_ADDRESS';